package com.example.healthydiet.websocket;

public enum WebSocketCode {
    REGISTER_SUCCESS,
    REGISTER_FAIL,

    LOGIN_SUCCESS,
    LOGIN_FAIL,

    FOOD_LIST_SUCCESS,
    FOOD_LIST_FAIL,

    FOOD_RECORD_ADD_SUCCESS,
    FOOD_RECORD_ADD_FAIL,

    FOOD_RECORD_GET_SUCCESS,
    FOOD_RECORD_GET_FAIL,

    FOOD_ITEM_GET_SUCCESS,
    FOOD_ITEM_GET_FAIL,

    UPDATE_USER_SUCCESS,
    UPDATE_USER_FAIL,

    FOOD_RECORD_UPDATE_SUCCESS,
    FOOD_RECORD_UPDATE_FAIL,

    FOOD_RECORD_DELETE_SUCCESS,
    FOOD_RECORD_DELETE_FAIL,

    FOOD_ITEM_UPDATE_SUCCESS,
    FOOD_ITEM_UPDATE_FAIL,

    FOOD_ITEM_ADD_SUCCESS,
    FOOD_ITEM_ADD_FAIL,

    FOOD_ITEM_DELETE_SUCCESS,
    FOOD_ITEM_DELETE_FAIL,

    WEIGHT_ADD_SUCCESS,
    WEIGHT_ADD_FAIL,
    WEIGHT_DELETE_SUCCESS,
    WEIGHT_DELETE_FAIL,
    WEIGHT_UPDATE_SUCCESS,
    WEIGHT_UPDATE_FAIL,
    WEIGHT_GET_SUCCESS,
    WEIGHT_GET_FAIL,
    WEIGHT_LATEST_GET_SUCCESS,
    WEIGHT_LATEST_GET_FAIL,

    ADMIN_LOGIN_SUCCESS,
    ADMIN_LOGIN_FAIL,
    ADMIN_UPDATE_SUCCESS,
    ADMIN_UPDATE_FAIL,
    GET_ALL_USERS_SUCCESS,
    GET_ALL_USERS_FAIL,
    BLOCK_USER_SUCCESS,
    BLOCK_USER_FAIL,
    UNBLOCK_USER_SUCCESS,
    UNBLOCK_USER_FAIL,

    FOOD_IDENTIFY_SUCCESS,
    FOOD_IDENTIFY_FAIL,

}

